---
title: "viz_part2"
author: "Ruiqi Xue"
date: "2023-10-03"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```



plot from last lecture
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temp plot", 
    x = "Min daily temp", 
    y = "Max daily temp", 
    color = "Location",
    caption = "Max vs min"
    ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15C", "0C", "15C")
    ) +
  viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "bottom")
```


## data argument ...

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() + 
  geom_smooth()

nyc_weather_df = weather_df |>
  filter(name == "CentralPark_NY")


hawaii_weather_df = weather_df |>
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = hawaii_weather_df)
```


## `patchwork`

```{r}
tmax_tmin_p = 
  weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) + 
  theme(legend.position = "none")

tmax_date_p = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(tmax_tmin_p + prcp_dens_p) / tmax_date_p
  
```

## data manipulation

```{r}
weather_df |>
  mutate(
    name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |>
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df |>
  mutate(
    name = fct_reorder(name, tmax)
  ) |>
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()
  
```


Complicated plot
```{r}

```











